### ISSUE TITLE
Possibility to save in db?

### ISSUE THREAD

**Issue by frontedbe** [enupal/translate#11]
Would be great if there's a possibility to save translations in db records (like this C2 plugin did => https://github.com/WHITEdevelopment/craft-translate )
Main issue with saving in translation files is that when saving translations on the production server by the client, the page gets refreshed and not all the modified translations get loaded from the translations file (somekind of lag on the server I dunno). When you refresh again, thén the translations get loaded correctly. Don't know if my explanation makes any sense? :D

**Comment by andrelopez** [comment]
Hi @mdominguez 

Sorry, but we don't have plans to save translations in the db while Craft handles it via translation files.

When you save a translation you need to switch to the `translated` filter

Please let us know if you have any other question

Best,

**Comment by frontedbe** [comment]
> When you save a translation you need to switch to the translated filter

What do you mean exactly?
The issue I'm having occurs in the controlpanel, after saving translations there's some kind of "lag" so the old translations get loaded instead of the ones I just saved.. But after a refresh the new ones occur :)

**Comment by stevenvandemoortele** [comment]
For everybody else experiencing lag when using this plugin:

The lag you're experiencing is most likely caused by php opcache.
You can fix this by adding the translations file to your opcache blacklist. 
If you don't manage your server yourself you'll need to contact your hosting provider to do this. 
[more info](https://en.code-bude.net/2017/02/11/how-to-disable-php-opcache-for-certain-directories/)
